# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080

# ===============================
# DATABASE CONFIGURATION (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=123

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# REMOVE DEFAULT SPRING SECURITY USER
# ===============================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration